server:
  port: "${APP_PORT}"
  allowOrigins:
    - "*"
  bodyLimit: "10M"
  timeout: 30 # Seconds

oauth2:
  googleRedirectUrl: "${GOOGLE_REDIRECT_URL}"
  googleClientID: "${GOOGLE_CLIENT_ID}"
  googleClientSecret: "${GOOGLE_CLIENT_SECRET}"
  scopes:
    - "openid"
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
  userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo"

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  dbname: "${DB_NAME}"
  sslmode: disable
  schema: public
