// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/task": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "List Tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsDataObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorBadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorInternalServerError"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Create task",
                "parameters": [
                    {
                        "description": "Request of Creating Task",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TaskCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsDataObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorBadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorInternalServerError"
                        }
                    }
                }
            }
        },
        "/task/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Delete task",
                "parameters": [
                    {
                        "type": "number",
                        "description": "id of task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsSuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorBadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorInternalServerError"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Update task",
                "parameters": [
                    {
                        "type": "number",
                        "description": "id of task",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request of Updating Task",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TaskUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsDataObject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorBadRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.DocsErrorInternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.TaskCreateReq": {
            "type": "object",
            "required": [
                "status",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 255
                },
                "status": {
                    "enum": [
                        "todo",
                        "doing",
                        "done"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.TaskStatus"
                        }
                    ]
                },
                "title": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "model.TaskUpdateReq": {
            "type": "object",
            "required": [
                "status",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 255
                },
                "status": {
                    "enum": [
                        "todo",
                        "doing",
                        "done"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.TaskStatus"
                        }
                    ]
                },
                "title": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "types.TaskStatus": {
            "type": "string",
            "enum": [
                "todo",
                "doing",
                "done"
            ],
            "x-enum-varnames": [
                "TaskStatusTodo",
                "TaskStatusDoing",
                "TaskStatusDone"
            ]
        },
        "utils.DocsDataObject": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "utils.DocsErrorBadRequest": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "details": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "message": {
                            "type": "string",
                            "example": "Bad request"
                        },
                        "status": {
                            "type": "integer",
                            "example": 400
                        }
                    }
                }
            }
        },
        "utils.DocsErrorInternalServerError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "details": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "message": {
                            "type": "string",
                            "example": "Internal Server Error"
                        },
                        "status": {
                            "type": "integer",
                            "example": 500
                        }
                    }
                }
            }
        },
        "utils.DocsErrorNotFound": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "details": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "message": {
                            "type": "string",
                            "example": "Not Found"
                        },
                        "status": {
                            "type": "integer",
                            "example": 404
                        }
                    }
                }
            }
        },
        "utils.DocsSuccessDetail": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "utils.DocsSuccessMessage": {
            "type": "object",
            "properties": {
                "success": {
                    "$ref": "#/definitions/utils.DocsSuccessDetail"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "GoGin API",
	Description:      "This is a sample server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
